"""
Pydantic models for API request/response validation.
"""

from pydantic import BaseModel, Field

# ── Request Models ───────────────────────────────────────────────────────────


class CitizenCreate(BaseModel):
    """Request body for POST /citizens — creates a citizen profile."""

    age: int = Field(..., ge=0, le=120, description="Citizen's age in years")
    gender: str = Field(
        ...,
        pattern="^(male|female)$",
        description="Gender: 'male' or 'female'",
    )
    caste: str = Field(
        ...,
        pattern="^(sc|st|obc|bc|ebc|general|minority)$",
        description="Caste category (lowercase)",
    )
    annual_income: int | None = Field(None, ge=0, description="Annual income in INR")
    annual_turnover: int | None = Field(
        None, ge=0, description="Annual business turnover in INR"
    )
    units_usage: int | None = Field(
        None, ge=0, description="Monthly electricity units usage"
    )
    business_type: str | None = Field(
        None, description="Type of business (if applicable)"
    )
    has_bank_account: bool = Field(False, description="Has a bank account?")
    has_gst: bool = Field(False, description="Has GST registration?")
    has_white_ration_card: bool = Field(False, description="Has a white ration card?")
    owns_land: bool = Field(False, description="Owns land?")


# ── Response Models ──────────────────────────────────────────────────────────


class CitizenResponse(BaseModel):
    """Response after creating a citizen profile."""

    id: str = Field(..., description="UUID generated by the server")
    age: int
    gender: str
    caste: str
    annual_income: int | None = None
    annual_turnover: int | None = None
    units_usage: int | None = None
    business_type: str | None = None
    satisfied_flags: list[str] = Field(
        default_factory=list,
        description="List of RequirementFlag names this citizen satisfies",
    )


class SchemeResponse(BaseModel):
    """Full scheme details with relationships."""

    id: str
    name: str
    telugu_name: str | None = None
    description: str | None = None
    telugu_description: str | None = None
    benefit_type: str | None = None
    amount_min: float | None = None
    amount_max: float | None = None
    interest_rate: str | None = None
    unit: str | None = None
    apply_url: str | None = None
    apply_offline: str | None = None
    helpline: str | None = None
    processing_time_days: int | None = None
    success_rate: str | None = None
    success_rank: int | None = None
    documents: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    business_types: list[str] = Field(default_factory=list)
    individual_types: list[str] = Field(default_factory=list)
    required_flags: list[str] = Field(default_factory=list)


class SchemeDetailResponse(SchemeResponse):
    """Extended scheme detail with eligibility criteria."""

    age_min: int | None = None
    age_max: int | None = None
    max_annual_income: int | None = None
    max_annual_turnover: int | None = None
    max_units_usage: int | None = None
    genders: list[str] = Field(default_factory=list)
    castes: list[str] = Field(default_factory=list)


class EligibleSchemeResponse(SchemeResponse):
    """Scheme returned as part of eligibility results."""

    pass


class RelatedSchemeResponse(BaseModel):
    """A related scheme with similarity metadata."""

    id: str
    name: str
    telugu_name: str | None = None
    description: str | None = None
    benefit_type: str | None = None
    amount_min: float | None = None
    amount_max: float | None = None
    interest_rate: str | None = None
    success_rate: str | None = None
    apply_url: str | None = None
    shared_tags: int = 0
    shared_flags: int = 0
    similarity_score: int = 0
    tags: list[str] = Field(default_factory=list)
    business_types: list[str] = Field(default_factory=list)
    individual_types: list[str] = Field(default_factory=list)


class HealthResponse(BaseModel):
    """Health check response."""

    status: str
    database: str
    message: str | None = None
