"""
Pydantic models for API request/response validation.
"""

from typing import Optional
from pydantic import BaseModel, Field


# ── Request Models ───────────────────────────────────────────────────────────

class CitizenCreate(BaseModel):
    """Request body for POST /citizens — creates a citizen profile."""

    age: int = Field(..., ge=0, le=120, description="Citizen's age in years")
    gender: str = Field(
        ...,
        pattern="^(male|female)$",
        description="Gender: 'male' or 'female'",
    )
    caste: str = Field(
        ...,
        pattern="^(sc|st|obc|bc|ebc|general|minority)$",
        description="Caste category (lowercase)",
    )
    annual_income: Optional[int] = Field(
        None, ge=0, description="Annual income in INR"
    )
    annual_turnover: Optional[int] = Field(
        None, ge=0, description="Annual business turnover in INR"
    )
    units_usage: Optional[int] = Field(
        None, ge=0, description="Monthly electricity units usage"
    )
    business_type: Optional[str] = Field(
        None, description="Type of business (if applicable)"
    )
    has_bank_account: bool = Field(False, description="Has a bank account?")
    has_gst: bool = Field(False, description="Has GST registration?")
    has_white_ration_card: bool = Field(False, description="Has a white ration card?")
    owns_land: bool = Field(False, description="Owns land?")


# ── Response Models ──────────────────────────────────────────────────────────

class CitizenResponse(BaseModel):
    """Response after creating a citizen profile."""

    id: str = Field(..., description="UUID generated by the server")
    age: int
    gender: str
    caste: str
    annual_income: Optional[int] = None
    annual_turnover: Optional[int] = None
    units_usage: Optional[int] = None
    business_type: Optional[str] = None
    satisfied_flags: list[str] = Field(
        default_factory=list,
        description="List of RequirementFlag names this citizen satisfies",
    )


class SchemeResponse(BaseModel):
    """Full scheme details with relationships."""

    id: str
    name: str
    telugu_name: Optional[str] = None
    description: Optional[str] = None
    telugu_description: Optional[str] = None
    benefit_type: Optional[str] = None
    amount_min: Optional[float] = None
    amount_max: Optional[float] = None
    interest_rate: Optional[str] = None
    unit: Optional[str] = None
    apply_url: Optional[str] = None
    apply_offline: Optional[str] = None
    helpline: Optional[str] = None
    processing_time_days: Optional[int] = None
    success_rate: Optional[str] = None
    success_rank: Optional[int] = None
    documents: list[str] = Field(default_factory=list)
    tags: list[str] = Field(default_factory=list)
    business_types: list[str] = Field(default_factory=list)
    individual_types: list[str] = Field(default_factory=list)
    required_flags: list[str] = Field(default_factory=list)


class SchemeDetailResponse(SchemeResponse):
    """Extended scheme detail with eligibility criteria."""

    age_min: Optional[int] = None
    age_max: Optional[int] = None
    max_annual_income: Optional[int] = None
    max_annual_turnover: Optional[int] = None
    max_units_usage: Optional[int] = None
    genders: list[str] = Field(default_factory=list)
    castes: list[str] = Field(default_factory=list)


class EligibleSchemeResponse(SchemeResponse):
    """Scheme returned as part of eligibility results."""
    pass


class RelatedSchemeResponse(BaseModel):
    """A related scheme with similarity metadata."""

    id: str
    name: str
    telugu_name: Optional[str] = None
    description: Optional[str] = None
    benefit_type: Optional[str] = None
    amount_min: Optional[float] = None
    amount_max: Optional[float] = None
    interest_rate: Optional[str] = None
    success_rate: Optional[str] = None
    apply_url: Optional[str] = None
    shared_tags: int = 0
    shared_flags: int = 0
    similarity_score: int = 0
    tags: list[str] = Field(default_factory=list)
    business_types: list[str] = Field(default_factory=list)
    individual_types: list[str] = Field(default_factory=list)


class HealthResponse(BaseModel):
    """Health check response."""

    status: str
    database: str
    message: Optional[str] = None
